//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board.Resources.MessageResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Board.Resources.MessageResources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码为空 的本地化字符串。
        /// </summary>
        internal static string LoginEmptyError {
            get {
                return ResourceManager.GetString("LoginEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码填写有误 的本地化字符串。
        /// </summary>
        internal static string LoginInfoError {
            get {
                return ResourceManager.GetString("LoginInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部服务器错误 的本地化字符串。
        /// </summary>
        internal static string LoginInternalServerError {
            get {
                return ResourceManager.GetString("LoginInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先升级再登陆 的本地化字符串。
        /// </summary>
        internal static string LoginNeedUpdate {
            get {
                return ResourceManager.GetString("LoginNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请联系管理员授权 的本地化字符串。
        /// </summary>
        internal static string LoginNoAuthorizationError {
            get {
                return ResourceManager.GetString("LoginNoAuthorizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定路径没找到 的本地化字符串。
        /// </summary>
        internal static string LoginNotFoundError {
            get {
                return ResourceManager.GetString("LoginNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序错误 的本地化字符串。
        /// </summary>
        internal static string LoginProgramError {
            get {
                return ResourceManager.GetString("LoginProgramError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程服务没启动 的本地化字符串。
        /// </summary>
        internal static string LoginServerNoRun {
            get {
                return ResourceManager.GetString("LoginServerNoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string LoginUnKnowError {
            get {
                return ResourceManager.GetString("LoginUnKnowError", resourceCulture);
            }
        }
    }
}
