//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board.Resources.ApiResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteRealtimeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteRealtimeResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Board.Resources.ApiResources.SiteRealtimeResource", typeof(SiteRealtimeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.sitemaster.com.cn/api_v1 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeDataClient {
            get {
                return ResourceManager.GetString("SiteRealtimeDataClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realtime/{0}/analyse 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeDataRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realtime/{0}/interaction_detail 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeInteractionDetailRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeInteractionDetailRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realtime/{0}/interaction_event 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeInteractionEventRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeInteractionEventRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realtime/{0}/interaction_summary 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeInteractionSummaryRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeInteractionSummaryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 my/sites 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeUserRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v2/campaigns/{0}/ 的本地化字符串。
        /// </summary>
        internal static string TrackCampaignDataRequest {
            get {
                return ResourceManager.GetString("TrackCampaignDataRequest", resourceCulture);
            }
        }
    }
}
