//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board.Resources.ApiResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Board.Resources.ApiResources.SystemResource", typeof(SystemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/AddDataCabin/{0}/{1}/{2}/{3}/{4}/{5} 的本地化字符串。
        /// </summary>
        internal static string AddDataCabinRequest {
            get {
                return ResourceManager.GetString("AddDataCabinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://localhost:46021 的本地化字符串。
        /// </summary>
        internal static string BoardServiceClient {
            get {
                return ResourceManager.GetString("BoardServiceClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/CopyWidget/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string CopyWidgetRequest {
            get {
                return ResourceManager.GetString("CopyWidgetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/deletedatacabin/{0}/{1}/{2} 的本地化字符串。
        /// </summary>
        internal static string DeleteDataCabinRequest {
            get {
                return ResourceManager.GetString("DeleteDataCabinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/DeleteWidget/{0} 的本地化字符串。
        /// </summary>
        internal static string DeleteWidgetRequest {
            get {
                return ResourceManager.GetString("DeleteWidgetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/GetBaseData/{0} 的本地化字符串。
        /// </summary>
        internal static string GetBaseDataRequest {
            get {
                return ResourceManager.GetString("GetBaseDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/GetConfigData/{0} 的本地化字符串。
        /// </summary>
        internal static string GetConfigDataRequest {
            get {
                return ResourceManager.GetString("GetConfigDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/GetDataBySystemType/{0} 的本地化字符串。
        /// </summary>
        internal static string GetDataBySystemTypeRequest {
            get {
                return ResourceManager.GetString("GetDataBySystemTypeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/GetListAndWidgetList/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string GetDataCabinListAndWidgetListRequest {
            get {
                return ResourceManager.GetString("GetDataCabinListAndWidgetListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/GetSystemList/{userId} 的本地化字符串。
        /// </summary>
        internal static string GetSystemListRequest {
            get {
                return ResourceManager.GetString("GetSystemListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://open.admaster.com.cn 的本地化字符串。
        /// </summary>
        internal static string GetTokenClient {
            get {
                return ResourceManager.GetString("GetTokenClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 oauth/access_token 的本地化字符串。
        /// </summary>
        internal static string GetTokenRequest {
            get {
                return ResourceManager.GetString("GetTokenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/GetWidgetList/{0}/{1}/{2}/{3} 的本地化字符串。
        /// </summary>
        internal static string GetWidgetListRequest {
            get {
                return ResourceManager.GetString("GetWidgetListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/GetWidget/{0} 的本地化字符串。
        /// </summary>
        internal static string GetWidgetRequest {
            get {
                return ResourceManager.GetString("GetWidgetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/IsAuthorization/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string IsAuthorizationRequest {
            get {
                return ResourceManager.GetString("IsAuthorizationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/SaveWidget 的本地化字符串。
        /// </summary>
        internal static string SaveWidgetRequest {
            get {
                return ResourceManager.GetString("SaveWidgetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/UpdateDataCabinDateType/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string UpdateDataCabinDateTypeRequest {
            get {
                return ResourceManager.GetString("UpdateDataCabinDateTypeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/UpdateDataCabinName/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string UpdateDataCabinNameRequest {
            get {
                return ResourceManager.GetString("UpdateDataCabinNameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/UpdateDataCabin/{0}/{1}/{2}/{3}/{4}/{5}/{6}/{7} 的本地化字符串。
        /// </summary>
        internal static string UpdateDataCabinRequest {
            get {
                return ResourceManager.GetString("UpdateDataCabinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/UpdateWidgetSize/{0}/{1}/{2} 的本地化字符串。
        /// </summary>
        internal static string UpdateWidgetSizeRequest {
            get {
                return ResourceManager.GetString("UpdateWidgetSizeRequest", resourceCulture);
            }
        }
    }
}
