//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board.Resources.ApiResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrackRealtimeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrackRealtimeResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Board.Resources.ApiResources.TrackRealtimeResource", typeof(TrackRealtimeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService/GetTrackRealtimeCampaignList/{0} 的本地化字符串。
        /// </summary>
        internal static string GetTrackRealtimeCampaignListRequest {
            get {
                return ResourceManager.GetString("GetTrackRealtimeCampaignListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v2/campaigns/{0}/creatives 的本地化字符串。
        /// </summary>
        internal static string TrackCreativeDataRequest {
            get {
                return ResourceManager.GetString("TrackCreativeDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v1/medias/{0} 的本地化字符串。
        /// </summary>
        internal static string TrackMediaDataRequest {
            get {
                return ResourceManager.GetString("TrackMediaDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v2/campaigns/{0}/placements 的本地化字符串。
        /// </summary>
        internal static string TrackPlacementDataRequest {
            get {
                return ResourceManager.GetString("TrackPlacementDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://m.trackmaster.com.cn 的本地化字符串。
        /// </summary>
        internal static string TrackRealtimeDataClient {
            get {
                return ResourceManager.GetString("TrackRealtimeDataClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v2/campaigns/{0}/reports/realtime?startDate={1}&amp;endDate={2}&amp;dimensions={3}&amp;metrics={4}&amp;maxResults={5}&amp;sort={6}&amp;startIndex=0&amp;access_token={7} 的本地化字符串。
        /// </summary>
        internal static string TrackRealtimeDataRequest {
            get {
                return ResourceManager.GetString("TrackRealtimeDataRequest", resourceCulture);
            }
        }
    }
}
