//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Board.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Board.Resources.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/AddDataCabin/{0}/{1}/{2}/{3}/{4}/{5} 的本地化字符串。
        /// </summary>
        internal static string AddDataCabinRequest {
            get {
                return ResourceManager.GetString("AddDataCabinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://42.62.14.46:46022 的本地化字符串。
        /// </summary>
        internal static string BoardServiceClient {
            get {
                return ResourceManager.GetString("BoardServiceClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/CopyWidget/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string CopyWidgetRequest {
            get {
                return ResourceManager.GetString("CopyWidgetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/deletedatacabin/{0}/{1}/{2} 的本地化字符串。
        /// </summary>
        internal static string DeleteDataCabinRequest {
            get {
                return ResourceManager.GetString("DeleteDataCabinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/DeleteWidget/{0} 的本地化字符串。
        /// </summary>
        internal static string DeleteWidgetRequest {
            get {
                return ResourceManager.GetString("DeleteWidgetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetBaseData/{0} 的本地化字符串。
        /// </summary>
        internal static string GetBaseDataRequest {
            get {
                return ResourceManager.GetString("GetBaseDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetConfigData/{0} 的本地化字符串。
        /// </summary>
        internal static string GetConfigDataRequest {
            get {
                return ResourceManager.GetString("GetConfigDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetDataBySystemType/{0} 的本地化字符串。
        /// </summary>
        internal static string GetDataBySystemTypeRequest {
            get {
                return ResourceManager.GetString("GetDataBySystemTypeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetListAndWidgetList/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string GetDataCabinListAndWidgetListRequest {
            get {
                return ResourceManager.GetString("GetDataCabinListAndWidgetListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetSponsorProgramList/{0} 的本地化字符串。
        /// </summary>
        internal static string GetSponsorProgramListRequest {
            get {
                return ResourceManager.GetString("GetSponsorProgramListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://open.admaster.com.cn 的本地化字符串。
        /// </summary>
        internal static string GetTokenClient {
            get {
                return ResourceManager.GetString("GetTokenClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 oauth/access_token 的本地化字符串。
        /// </summary>
        internal static string GetTokenRequest {
            get {
                return ResourceManager.GetString("GetTokenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetTrackRealtimeCampaignList/{0} 的本地化字符串。
        /// </summary>
        internal static string GetTrackRealtimeCampaignListRequest {
            get {
                return ResourceManager.GetString("GetTrackRealtimeCampaignListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetWidgetList/{0}/{1}/{2}/{3} 的本地化字符串。
        /// </summary>
        internal static string GetWidgetListRequest {
            get {
                return ResourceManager.GetString("GetWidgetListRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetWidget/{0} 的本地化字符串。
        /// </summary>
        internal static string GetWidgetRequest {
            get {
                return ResourceManager.GetString("GetWidgetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/IsAuthorization/{0} 的本地化字符串。
        /// </summary>
        internal static string IsAuthorizationRequest {
            get {
                return ResourceManager.GetString("IsAuthorizationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/SaveWidget 的本地化字符串。
        /// </summary>
        internal static string SaveWidgetRequest {
            get {
                return ResourceManager.GetString("SaveWidgetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://v1.site.admasterapi.com 的本地化字符串。
        /// </summary>
        internal static string SiteDataClient {
            get {
                return ResourceManager.GetString("SiteDataClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sites 的本地化字符串。
        /// </summary>
        internal static string SiteDataRequest {
            get {
                return ResourceManager.GetString("SiteDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://v1.site.admasterapi.com 的本地化字符串。
        /// </summary>
        internal static string SiteDataSourceClient {
            get {
                return ResourceManager.GetString("SiteDataSourceClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 my/sites 的本地化字符串。
        /// </summary>
        internal static string SiteDataSourceRequest {
            get {
                return ResourceManager.GetString("SiteDataSourceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://www.sitemaster.com.cn/api_v1 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeDataClient {
            get {
                return ResourceManager.GetString("SiteRealtimeDataClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realtime/{0}/analyse 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeDataRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realtime/{0}/interaction_detail 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeInteractionDetailRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeInteractionDetailRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realtime/{0}/interaction_event 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeInteractionEventRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeInteractionEventRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 realtime/{0}/interaction_summary 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeInteractionSummaryRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeInteractionSummaryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 my/sites 的本地化字符串。
        /// </summary>
        internal static string SiteRealtimeUserRequest {
            get {
                return ResourceManager.GetString("SiteRealtimeUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/GetSponsorData/{0}/{1}/{2}/{3}/{4} 的本地化字符串。
        /// </summary>
        internal static string SponsorDataRequest {
            get {
                return ResourceManager.GetString("SponsorDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://m.trackmaster.com.cn/ 的本地化字符串。
        /// </summary>
        internal static string TrackAnalysisDataClient {
            get {
                return ResourceManager.GetString("TrackAnalysisDataClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 track_api/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string TrackAnalysisDataRequest {
            get {
                return ResourceManager.GetString("TrackAnalysisDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://42.62.14.46:8615 的本地化字符串。
        /// </summary>
        internal static string TrackAnalysisDataServer {
            get {
                return ResourceManager.GetString("TrackAnalysisDataServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v2/campaigns/{0}/ 的本地化字符串。
        /// </summary>
        internal static string TrackCampaignDataRequest {
            get {
                return ResourceManager.GetString("TrackCampaignDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v2/campaigns/{0}/creatives 的本地化字符串。
        /// </summary>
        internal static string TrackCreativeDataRequest {
            get {
                return ResourceManager.GetString("TrackCreativeDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v1/medias/{0} 的本地化字符串。
        /// </summary>
        internal static string TrackMediaDataRequest {
            get {
                return ResourceManager.GetString("TrackMediaDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v2/campaigns/{0}/placements 的本地化字符串。
        /// </summary>
        internal static string TrackPlacementDataRequest {
            get {
                return ResourceManager.GetString("TrackPlacementDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://m.trackmaster.com.cn 的本地化字符串。
        /// </summary>
        internal static string TrackRealtimeDataClient {
            get {
                return ResourceManager.GetString("TrackRealtimeDataClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 api_v2/campaigns/{0}/reports/realtime?startDate={1}&amp;endDate={2}&amp;dimensions={3}&amp;metrics={4}&amp;maxResults={5}&amp;sort={6}&amp;startIndex=0&amp;access_token={7} 的本地化字符串。
        /// </summary>
        internal static string TrackRealtimeDataRequest {
            get {
                return ResourceManager.GetString("TrackRealtimeDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/UpdateDataCabinDateType/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string UpdateDataCabinDateTypeRequest {
            get {
                return ResourceManager.GetString("UpdateDataCabinDateTypeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/UpdateDataCabinName/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string UpdateDataCabinNameRequest {
            get {
                return ResourceManager.GetString("UpdateDataCabinNameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/UpdateDataCabin/{0}/{1}/{2}/{3}/{4}/{5}/{6}/{7} 的本地化字符串。
        /// </summary>
        internal static string UpdateDataCabinRequest {
            get {
                return ResourceManager.GetString("UpdateDataCabinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BoardService2/UpdateWidgetSize/{0}/{1}/{2} 的本地化字符串。
        /// </summary>
        internal static string UpdateWidgetSizeRequest {
            get {
                return ResourceManager.GetString("UpdateWidgetSizeRequest", resourceCulture);
            }
        }
    }
}
